
const flashcards = {
  numbers: [
    { id: 1, en: "one", th: "หนึ่ง" },
    { id: 2, en: "two", th: "สอง" },
    { id: 3, en: "three", th: "สาม" },
    { id: 4, en: "four", th: "สี่" },
    { id: 5, en: "five", th: "ห้า" },
    { id: 6, en: "six", th: "หก" },
    { id: 7, en: "seven", th: "เจ็ด" },
    { id: 8, en: "eight", th: "แปด" },
    { id: 9, en: "nine", th: "เก้า" },
    { id: 10, en: "zero", th: "ศูนย์" },
    { id: 10, en: "ten", th: "สิบ" },
    { id: 10, en: "eleven", th: "สิบเอ็ด" },
    { id: 10, en: "twenty", th: "ยี่สิบ" },
    { id: 10, en: "one hundred", th: "ร้อย" },
    { id: 10, en: "one thousand", th: "พัน" },
    { id: 10, en: "ten thousand", th: "หมื่น" },
    { id: 10, en: "hundred thousand", th: "แสน" },
    { id: 10, en: "one million", th: "ล้าน" },
  ],
  days: [
    { id: 1, en: "monday", th: "วันจันทร์" },
    { id: 2, en: "tuesday", th: "วันอังคาร" },
    { id: 3, en: "wednesday", th: "วันพุธ" },
    { id: 4, en: "thursday", th: "วันพฤหัสบดี" },
    { id: 5, en: "friday", th: "วันศุกร์" },
    { id: 6, en: "saturday", th: "วันเสาร์" },
    { id: 7, en: "sunday", th: "วันอาทิตย์" },
    { id: 8, en: "birthday", th: "วันเกิด" },
    { id: 9, en: "holiday", th: "วันหยุด" },
    { id: 10, en: "week", th: "สัปดาห์" },
    { id: 11, en: "month", th: "เดือน" },
  ],
  colors: [
    { id: 1, en: "color", th: "สี" },
    { id: 2, en: "red", th: "แดง" },
    { id: 3, en: "green", th: "เขียว" },
    { id: 4, en: "blue", th: "น้ำเงิน" },
    { id: 5, en: "yellow", th: "เหลือง" },
    { id: 6, en: "white", th: "ขาว" },
    { id: 7, en: "black", th: "ดำ" },
    { id: 8, en: "pink", th: "ชมพู" },
    { id: 9, en: "orange", th: "ส้ม" },
    { id: 10, en: "brown", th: "น้ำตาล" },
    { id: 11, en: "violet", th: "ม่วง" },
    { id: 12, en: "gray", th: "เทา" },
    { id: 13, en: "light blue", th: "ฟ้า" },
  ],
  "adjectives 1": [
    { id: 1, en: "pretty", th: "สวย" },
    { id: 2, en: "cute", th: "น่ารัก" },
    { id: 3, en: "handsome", th: "หล่อ" },
    { id: 4, en: "ugly", th: "น่าเกลียด" },
    { id: 5, en: "good", th: "ดี" },
    { id: 6, en: "bad", th: "แย่" },
    { id: 7, en: "new", th: "ใหม่" },
    { id: 8, en: "old", th: "เก่า" },
    { id: 9, en: "long", th: "ยาว" },
    { id: 10, en: "short", th: "สั้น" },
  ],
  "adjectives 2": [
    { id: 1, en: "cheap", th: "ถูก" },
    { id: 2, en: "expensive", th: "แพง" },
    { id: 3, en: "fast", th: "เร็ว" },
    { id: 4, en: "slow", th: "ช้า" },
    { id: 5, en: "many", th: "มาก" },
    { id: 6, en: "few", th: "น้อย" },
    { id: 7, en: "hot", th: "ร้อน" },
    { id: 8, en: "cold", th: "เย็น" },
    { id: 9, en: "big", th: "ใหญ่" },
    { id: 10, en: "small", th: "เล็ก" },
    { id: 11, en: "delicious", th: "อร่อย" },
    { id: 12, en: "spicy", th: "เผ็ด" },
    { id: 13, en: "loud", th: "ดัง" },
    { id: 14, en: "quiet", th: "เงียบ" },
  ],
  "verbs 1": [
    { id: 1, en: "hear", th: "ได้ยิน" },
    { id: 2, en: "listen", th: "ฟัง" },
    { id: 3, en: "do", th: "ทำ" },
    { id: 4, en: "walk", th: "เดิน" },
    { id: 5, en: "run", th: "วิ่ง" },
    { id: 6, en: "jump", th: "กระโดด" },
    { id: 7, en: "sing", th: "ร้องเพลง" },
    { id: 8, en: "dance", th: "เต้น" },
    { id: 9, en: "go", th: "ไป" },
    { id: 10, en: "eat", th: "กิน" },
    { id: 11, en: "drink", th: "ดื่ม" },
    { id: 12, en: "read", th: "อ่าน" },
    { id: 13, en: "write", th: "เขียน" },
    { id: 14, en: "sleep", th: "นอน" },
    { id: 15, en: "sit", th: "นั่ง" },
    { id: 16, en: "stand", th: "ยืน" },
    { id: 17, en: "like", th: "ชอบ" },
    { id: 18, en: "want", th: "อยาก" },
    { id: 19, en: "open", th: "เปิด" },
    { id: 20, en: "close", th: "ปิด" },
    { id: 21, en: "sell", th: "ขาย" },
    { id: 22, en: "buy", th: "ซื้อ" },
    { id: 23, en: "hate", th: "เกลียด" },
    { id: 24, en: "see", th: "ดเห็น" },
    { id: 25, en: "watch", th: "ดู" },
  ],
  "verbs 2": [
    { id: 1, en: "know", th: "รู้" },
    { id: 2, en: "understand", th: "เข้าใจ" },
    { id: 3, en: "remember", th: "จำ" },
    { id: 4, en: "promise", th: "สัญญา" },
    { id: 5, en: "think", th: "คิด" },
    { id: 6, en: "taste", th: "ลิ้มรส" },
    { id: 7, en: "choose", th: "เลือก" },
    { id: 8, en: "ask", th: "ถาม" },
    { id: 9, en: "answer", th: "ตอบ" },
    { id: 10, en: "push", th: "ดัน" },
    { id: 11, en: "pull", th: "ดึง" },
    { id: 12, en: "bring", th: "นำมา" },
    { id: 13, en: "love", th: "รัก" },
    { id: 14, en: "cook", th: "ทำอาหาร" },
    { id: 15, en: "touch", th: "สัมผัส" },
    { id: 16, en: "change", th: "เปลี่ยน" },
    { id: 17, en: "find", th: "หา" },
  ],
  "nouns 1": [
    { id: 1, en: "bag", th: "กระเป๋า" },
    { id: 2, en: "umbrella", th: "ร่ม" },
    { id: 3, en: "pen", th: "ปากกา" },
    { id: 4, en: "pencil", th: "ดินสอ" },
    { id: 5, en: "pencil", th: "ดินสอ" },
    { id: 6, en: "t shirt", th: "เสื้อยืด" },
    { id: 7, en: "pants", th: "กางเกง" },
    { id: 8, en: "shorts", th: "กางเกงขาสั้น" },
    { id: 9, en: "socks", th: "ถุงเท้า" },
    { id: 10, en: "shoes", th: "รองเท้า" },
    { id: 11, en: "underwear", th: "ชุดชั้นใน" },
    { id: 12, en: "work", th: "ทำงาน" },
    { id: 13, en: "book", th: "หนังสือ" },
    { id: 14, en: "money", th: "เงิน" },
    { id: 15, en: "key", th: "กุญแจ" },
    { id: 16, en: "wallet", th: "กระเป๋าสตางค์" },
    { id: 17, en: "phone", th: "โทรศัพท์" },
    { id: 18, en: "house", th: "บ้าน" },
    { id: 19, en: "door", th: "ประตู" },
    { id: 20, en: "window", th: "หน้าต่าง" },
  ],
  "nouns 2 - body": [
    { id: 1, en: "ear", th: "หู" },
    { id: 2, en: "eye", th: "ตา" },
    { id: 3, en: "nose", th: "จมูก" },
    { id: 4, en: "mouth", th: "ปาก" },
    { id: 5, en: "lip", th: "ริมฝีปาก" },
    { id: 6, en: "face", th: "ใบหน้า" },
    { id: 7, en: "head", th: "หัว" },
    { id: 8, en: "body", th: "ร่างกาย" },
    { id: 9, en: "shoulder", th: "ไหล่" },
    { id: 10, en: "back", th: "หลัง" },
    { id: 11, en: "arm", th: "แขน" },
    { id: 12, en: "knee", th: "เข่า" },
    { id: 13, en: "leg", th: "ขา" },
    { id: 14, en: "hand", th: "มือ" },
    { id: 15, en: "finger", th: "นิ้ว" },
    { id: 16, en: "foot", th: "เท้า" },
    { id: 17, en: "toe", th: "นิ้วเท้า" },
  ],
  "nouns 3 - abstract": [
    { id: 1, en: "bangkok", th: "กรุงเทพฯ" },
    { id: 1, en: "friend", th: "เพื่อน" },
    { id: 1, en: "dream", th: "ความฝัน" },
    { id: 1, en: "truth", th: "ความจริง" },
    { id: 1, en: "gift", th: "ของขวัญ" },
    { id: 1, en: "God", th: "พระเจ้า" },
    { id: 1, en: "word", th: "คำ" },
    { id: 1, en: "sentence", th: "ประโยค" },
    { id: 1, en: "question", th: "คำถาม" },
    { id: 1, en: "answer", th: "คำตอบ" },
    { id: 1, en: "price", th: "ราคา" },
    { id: 1, en: "place", th: "สถานที่" },
    { id: 1, en: "today", th: "วันนี้" },
    { id: 1, en: "yesterday", th: "เมื่อวาน" },
    { id: 1, en: "tomorrow", th: "พรุ่งนี้" },
    { id: 1, en: "life", th: "ชีวิต" },
    { id: 1, en: "death", th: "ความตาย" },
    { id: 1, en: "animal", th: "สัตว์" },
    { id: 1, en: "plant", th: "พืช" },
    { id: 1, en: "health", th: "สุขภาพ" },
  ],
};

export {
  flashcards,
}
