
const flashcards = {
  numbers: [
    { id: 1, en: "one", th: "หนึ่ง" },
    { id: 2, en: "two", th: "สอง" },
    { id: 3, en: "three", th: "สาม" },
    { id: 4, en: "four", th: "สี่" },
    { id: 5, en: "five", th: "ห้า" },
    { id: 6, en: "six", th: "หก" },
    { id: 7, en: "seven", th: "เจ็ด" },
    { id: 8, en: "eight", th: "แปด" },
    { id: 9, en: "nine", th: "เก้า" },
    { id: 10, en: "zero", th: "ศูนย์" },
    { id: 10, en: "ten", th: "สิบ" },
    { id: 10, en: "eleven", th: "สิบเอ็ด" },
    { id: 10, en: "twenty", th: "ยี่สิบ" },
    { id: 10, en: "one hundred", th: "ร้อย" },
    { id: 10, en: "one thousand", th: "พัน" },
    { id: 10, en: "ten thousand", th: "หมื่น" },
    { id: 10, en: "hundred thousand", th: "แสน" },
    { id: 10, en: "one million", th: "ล้าน" },
  ],
  days: [
    { id: 1, en: "monday", th: "วันจันทร์" },
    { id: 2, en: "tuesday", th: "วันอังคาร" },
    { id: 3, en: "wednesday", th: "วันพุธ" },
    { id: 4, en: "thursday", th: "วันพฤหัสบดี" },
    { id: 5, en: "friday", th: "วันศุกร์" },
    { id: 6, en: "saturday", th: "วันเสาร์" },
    { id: 7, en: "sunday", th: "วันอาทิตย์" },
    { id: 8, en: "birthday", th: "วันเกิด" },
    { id: 9, en: "holiday", th: "วันหยุด" },
    { id: 10, en: "week", th: "สัปดาห์" },
    { id: 11, en: "month", th: "เดือน" },
  ],
  colors: [
    { id: 1, en: "color", th: "สี" },
    { id: 2, en: "red", th: "แดง" },
    { id: 3, en: "green", th: "เขียว" },
    { id: 4, en: "blue", th: "น้ำเงิน" },
    { id: 5, en: "yellow", th: "เหลือง" },
    { id: 6, en: "white", th: "ขาว" },
    { id: 7, en: "black", th: "ดำ" },
    { id: 8, en: "pink", th: "ชมพู" },
    { id: 9, en: "orange", th: "ส้ม" },
    { id: 10, en: "brown", th: "น้ำตาล" },
    { id: 11, en: "violet", th: "ม่วง" },
    { id: 12, en: "gray", th: "เทา" },
    { id: 13, en: "light blue", th: "ฟ้า" },
  ],
  "adjectives 1": [
    { id: 1, en: "pretty", th: "สวย" },
    { id: 2, en: "cute", th: "น่ารัก" },
    { id: 3, en: "handsome", th: "หล่อ" },
    { id: 4, en: "ugly", th: "น่าเกลียด" },
    { id: 5, en: "good", th: "ดี" },
    { id: 6, en: "bad", th: "แย่" },
    { id: 7, en: "new", th: "ใหม่" },
    { id: 8, en: "old", th: "เก่า" },
    { id: 9, en: "long", th: "ยาว" },
    { id: 10, en: "short", th: "สั้น" },
  ],
  "adjectives 2": [
    { id: 1, en: "cheap", th: "ถูก" },
    { id: 2, en: "expensive", th: "แพง" },
    { id: 3, en: "fast", th: "เร็ว" },
    { id: 4, en: "slow", th: "ช้า" },
    { id: 5, en: "many", th: "มาก" },
    { id: 6, en: "few", th: "น้อย" },
    { id: 7, en: "hot", th: "ร้อน" },
    { id: 8, en: "cold", th: "เย็น" },
    { id: 9, en: "big", th: "ใหญ่" },
    { id: 10, en: "small", th: "เล็ก" },
    { id: 11, en: "delicious", th: "อร่อย" },
    { id: 12, en: "spicy", th: "เผ็ด" },
    { id: 13, en: "loud", th: "ดัง" },
    { id: 14, en: "quiet", th: "เงียบ" },
  ],
  "adjectives 3 - emotions": [
    { id: 1, en: "feeling", th: "ความรู้สึก" },
    { id: 2, en: "happy", th: "มีความสุข" },
    { id: 3, en: "sad", th: "ฉันกำลังเสียใจ", enSub: "I am sad" },
    { id: 4, en: "afraid", th: "กลัว" },
    { id: 5, en: "strong", th: "โกรธ" },
    { id: 6, en: "weak", th: "อ่อนแอ" },
    { id: 7, en: "excited", th: "ตื่นเต้น" },
    { id: 8, en: "tired", th: "เหนื่อย" },
    { id: 9, en: "bored", th: "เบื่อ" },
    { id: 10, en: "hurt", th: "เจ็บ" },
    { id: 11, en: "pain", th: "ปวด" },
    { id: 12, en: "lonely", th: "เหงา" },
  ],
  "adjectives 4": [
    { id: 1, en: "salty", th: "เค็ม" },
    { id: 2, en: "sweet", th: "หวาน" },
    { id: 3, en: "wet", th: "เปียก" },
    { id: 4, en: "dry", th: "แห้ง" },
    { id: 5, en: "correct", th: "ถูกต้อง" },
    { id: 6, en: "wrong", th: "ผิด" },
  ],
  "verbs 1": [
    { id: 1, en: "hear", th: "ได้ยิน" },
    { id: 2, en: "listen", th: "ฟัง" },
    { id: 3, en: "do", th: "ทำ" },
    { id: 4, en: "walk", th: "เดิน" },
    { id: 5, en: "run", th: "วิ่ง" },
    { id: 6, en: "jump", th: "กระโดด" },
    { id: 7, en: "sing", th: "ร้องเพลง" },
    { id: 8, en: "dance", th: "เต้น" },
    { id: 9, en: "go", th: "ไป" },
    { id: 10, en: "eat", th: "กิน" },
    { id: 11, en: "drink", th: "ดื่ม" },
    { id: 12, en: "read", th: "อ่าน" },
    { id: 13, en: "write", th: "เขียน" },
    { id: 14, en: "sleep", th: "นอน" },
    { id: 15, en: "sit", th: "นั่ง" },
    { id: 16, en: "stand", th: "ยืน" },
    { id: 17, en: "like", th: "ชอบ" },
    { id: 18, en: "want", th: "อยาก" },
    { id: 19, en: "open", th: "เปิด" },
    { id: 20, en: "close", th: "ปิด" },
    { id: 21, en: "sell", th: "ขาย" },
    { id: 22, en: "buy", th: "ซื้อ" },
    { id: 23, en: "hate", th: "เกลียด" },
    { id: 24, en: "see", th: "เห็น" },
    { id: 25, en: "watch", th: "ดู" },
    { id: 26, en: "forget", th: "ลืม" },
  ],
  "verbs 2": [
    { id: 1, en: "know", th: "รู้" },
    { id: 2, en: "understand", th: "เข้าใจ" },
    { id: 3, en: "remember", th: "จำ" },
    { id: 4, en: "promise", th: "สัญญา" },
    { id: 5, en: "think", th: "คิด" },
    { id: 6, en: "taste", th: "ลิ้มรส" },
    { id: 7, en: "choose", th: "เลือก" },
    { id: 8, en: "ask", th: "ถาม" },
    { id: 9, en: "answer", th: "ตอบ" },
    { id: 10, en: "push", th: "ดัน" },
    { id: 11, en: "pull", th: "ดึง" },
    { id: 12, en: "bring", th: "นำมา" },
    { id: 13, en: "love", th: "รัก" },
    { id: 14, en: "cook", th: "ทำอาหาร" },
    { id: 15, en: "touch", th: "สัมผัส" },
    { id: 16, en: "change", th: "เปลี่ยน" },
    { id: 17, en: "find", th: "หา" },
  ],
  "verbs 3": [
    { id: 1, en: "play", th: "เล่น" },
    { id: 2, en: "dream", th: "ฝัน" },
    { id: 3, en: "hope", th: "หวัง" },
    { id: 4, en: "have", th: "มี" },
    { id: 5, en: "drive", th: "ขับ" },
    { id: 6, en: "teach", th: "สอน" },
    { id: 7, en: "laugh", th: "หัวเราะ" },
    { id: 8, en: "speak", th: "พูด" },
    { id: 9, en: "draw", th: "วาด" },
    { id: 10, en: "can", th: "สามารถ" },
    { id: 11, en: "give", th: "ให้" },
    { id: 12, en: "receive", th: "ได้รับ" },
    { id: 13, en: "start", th: "เริ่ม" },
    { id: 14, en: "end", th: "จบ" },
    { id: 15, en: "try", th: "พยายาม" },
    { id: 16, en: "exercise", th: "ออกกำลังกาย" },
  ],
  "nouns 1": [
    { id: 1, en: "bag", th: "กระเป๋า" },
    { id: 2, en: "umbrella", th: "ร่ม" },
    { id: 3, en: "pen", th: "ปากกา" },
    { id: 4, en: "pencil", th: "ดินสอ" },
    { id: 5, en: "pencil", th: "ดินสอ" },
    { id: 6, en: "t shirt", th: "เสื้อยืด" },
    { id: 7, en: "pants", th: "กางเกง" },
    { id: 8, en: "shorts", th: "กางเกงขาสั้น" },
    { id: 9, en: "socks", th: "ถุงเท้า" },
    { id: 10, en: "shoes", th: "รองเท้า" },
    { id: 11, en: "underwear", th: "ชุดชั้นใน" },
    { id: 12, en: "work", th: "ทำงาน" },
    { id: 13, en: "book", th: "หนังสือ" },
    { id: 14, en: "money", th: "เงิน" },
    { id: 15, en: "key", th: "กุญแจ" },
    { id: 16, en: "wallet", th: "กระเป๋าสตางค์" },
    { id: 17, en: "phone", th: "โทรศัพท์" },
    { id: 18, en: "house", th: "บ้าน" },
    { id: 19, en: "door", th: "ประตู" },
    { id: 20, en: "window", th: "หน้าต่าง" },
  ],
  "nouns 2 - body": [
    { id: 1, en: "ear", th: "หู" },
    { id: 2, en: "eye", th: "ตา" },
    { id: 3, en: "nose", th: "จมูก" },
    { id: 4, en: "mouth", th: "ปาก" },
    { id: 5, en: "lip", th: "ริมฝีปาก" },
    { id: 6, en: "face", th: "ใบหน้า" },
    { id: 7, en: "head", th: "หัว" },
    { id: 8, en: "body", th: "ร่างกาย" },
    { id: 9, en: "shoulder", th: "ไหล่" },
    { id: 10, en: "back", th: "หลัง" },
    { id: 11, en: "arm", th: "แขน" },
    { id: 12, en: "knee", th: "เข่า" },
    { id: 13, en: "leg", th: "ขา" },
    { id: 14, en: "hand", th: "มือ" },
    { id: 15, en: "finger", th: "นิ้ว" },
    { id: 16, en: "foot", th: "เท้า" },
    { id: 17, en: "toe", th: "นิ้วเท้า" },
  ],
  "nouns 3 - abstract": [
    { id: 1, en: "bangkok", th: "กรุงเทพฯ" },
    { id: 1, en: "friend", th: "เพื่อน" },
    { id: 1, en: "dream", th: "ความฝัน" },
    { id: 1, en: "truth", th: "ความจริง" },
    { id: 1, en: "gift", th: "ของขวัญ" },
    { id: 1, en: "God", th: "พระเจ้า" },
    { id: 1, en: "word", th: "คำ" },
    { id: 1, en: "sentence", th: "ประโยค" },
    { id: 1, en: "question", th: "คำถาม" },
    { id: 1, en: "answer", th: "คำตอบ" },
    { id: 1, en: "price", th: "ราคา" },
    { id: 1, en: "place", th: "สถานที่" },
    { id: 1, en: "today", th: "วันนี้" },
    { id: 1, en: "yesterday", th: "เมื่อวาน" },
    { id: 1, en: "tomorrow", th: "พรุ่งนี้" },
    { id: 1, en: "life", th: "ชีวิต" },
    { id: 1, en: "death", th: "ความตาย" },
    { id: 1, en: "animal", th: "สัตว์" },
    { id: 1, en: "plant", th: "พืช" },
    { id: 1, en: "health", th: "สุขภาพ" },
  ],
  "nouns 4": [
    { id: 1, en: "dog", th: "สุนัข" },
    { id: 2, en: "cat", th: "แมว" },
    { id: 3, en: "bird", th: "นก" },
    { id: 4, en: "snake", th: "งู" },
    { id: 5, en: "tiger", th: "เสือ" },
    { id: 6, en: "lion", th: "สิงโต" },
    { id: 7, en: "flower", th: "ดอกไม้" },
    { id: 8, en: "pig", th: "หมู" },
    { id: 9, en: "chicken", th: "ไก่" },
    { id: 10, en: "egg", th: "ไข่" },
    { id: 11, en: "fish", th: "ปลา" },
    { id: 12, en: "meat", th: "เนื้อ" },
  ],
  "nouns 5 - places": [
    { id: 1, en: "building", th: "อาคาร" },
    { id: 2, en: "hospital", th: "โรงพยาบาล" },
    { id: 3, en: "school", th: "โรงเรียน" },
    { id: 4, en: "hotel", th: "โรงแรม" },
    { id: 5, en: "park", th: "สวนสาธารณะ" },
    { id: 6, en: "market", th: "ตลาด" },
    { id: 7, en: "station", th: "สถานี" },
    { id: 8, en: "street", th: "ถนน" },
    { id: 9, en: "(soi)", th: "ซอย", enSub: "little street" },
    { id: 10, en: "river", th: "แม่น้ำ" },
    { id: 11, en: "bridge", th: "สะพาน" },
    { id: 12, en: "beach", th: "ชายหาด" },
    { id: 13, en: "sea", th: "ทะเล" },
  ],
  "nouns 6": [
    { id: 1, en: "light", th: "แสง" },
    { id: 2, en: "sound", th: "เสียง" },
    { id: 3, en: "smile", th: "ยิ้ม" },
    { id: 4, en: "funny", th: "ตลก" },
    { id: 5, en: "hug", th: "กอด" },
    { id: 6, en: "kiss", th: "จูบ" },
    { id: 7, en: "past", th: "อดีต" },
    { id: 8, en: "future", th: "อนาคต" },
    { id: 9, en: "world", th: "โลก" },
    { id: 10, en: "movie", th: "ภาพยนตร์" },
    { id: 11, en: "family", th: "ครอบครัว" },
    { id: 12, en: "father", th: "พ่อ" },
    { id: 13, en: "mother", th: "แม่" },
  ],
  "nouns 7 - vehicles": [
    { id: 1, en: "car", th: "รถยนต์" },
    { id: 2, en: "airplane", th: "เครื่องบิน" },
    { id: 3, en: "train", th: "รถไฟ" },
    { id: 4, en: "sky train", th: "รถไฟฟ้า" },
    { id: 5, en: "subway", th: "รถไฟใต้ดิน" },
    { id: 6, en: "(tuk tuk)", th: "ตุ๊ก ตุ๊ก" },
    { id: 7, en: "taxi", th: "แท็กซี่" },
    { id: 8, en: "bus", th: "รสบัส" },
    { id: 9, en: "boat", th: "เรือ" },
    { id: 10, en: "bicycle", th: "จักรยาน" },
  ],
  "nouns 8": [
    { id: 1, en: "sun", th: "พระอาทิตย์" },
    { id: 2, en: "moon", th: "พระจันทร์" },
    { id: 3, en: "wind", th: "ลม" },
    { id: 4, en: "tree", th: "ต้นไม้" },
    { id: 5, en: "star", th: "ดาว" },
    { id: 6, en: "Siam", th: "สยาม" },
    { id: 7, en: "wat Arun", th: "วัดอรุณ" },
    { id: 8, en: "wat Pho", th: "วัดโพธิ์" },
    { id: 9, en: "Chatuchak ", th: "จตุจักร" },
  ],
  "nouns 9 - food": [
    { id: 1, en: "salt", th: "เกลือ" },
    { id: 2, en: "sugar", th: "น้ำตาล" },
    { id: 3, en: "fruit", th: "ผลไม้" },
    { id: 4, en: "vegetable", th: "ผัก" },
    { id: 5, en: "mango", th: "มะม่วง" },
    { id: 6, en: "apple", th: "แอปเปิ้ล" },
    { id: 7, en: "watermelon", th: "แตงโม" },
    { id: 8, en: "pineapple", th: "สับปะรด" },
    { id: 9, en: "orange", th: "ส้ม" },
    { id: 10, en: "onion", th: "หัวหอม" },
    { id: 11, en: "garlic", th: "กระเทียม" },
  ],
  "nouns 10": [
    { id: 1, en: "doctor", th: "หมอ" },
    { id: 2, en: "teacher", th: "ครู" },
    { id: 3, en: "police officer", th: "ตำรวจ" },
    { id: 4, en: "driver", th: "คนขับ" },
    { id: 5, en: "vendor", th: "ผู้ขาย" },
    { id: 6, en: "airport", th: "สนามบิน" },
    { id: 7, en: "department store", th: "ห้างสรรพสินค้า" },
    { id: 8, en: "midnight", th: "เที่ยงคืน" },
    { id: 9, en: "noon", th: "ตอนเที่ยง" },
    { id: 10, en: "morning", th: "เช้า" },
    { id: 11, en: "afternoon", th: "บ่าย" },
    { id: 12, en: "night", th: "เย็น / คืน" },
  ],
  "grammar 1": [
    { id: 1, en: "Thai", th: "ไทย" },
    { id: 2, en: "(gamlang)", th: "กำลัง", enSub: "ongoing action" },
    { id: 3, en: "(laaew)", th: "แล้ว", enSub: "already" },
    { id: 4, en: "(luey)", th: "เลย", enSub: "do immediately / ... so much / not ... at all" },
    { id: 5, en: "(kuey)", th: "เคย", enSub: "never (verb)" },
    { id: 6, en: "(mai)", th: "ไหม", enSub: "question" },
    { id: 7, en: "(ja)", th: "จะ", enSub: "future tense" },
    { id: 8, en: "(mak)", th: "มากะ", enSub: "a lot / so much" },
    { id: 9, en: "(-er)", th: "กว่า", enSub: "(verb) -er" },
    { id: 10, en: "(-est)", th: "ที่สุด", enSub: "(verb) -est" },
    { id: 11, en: "(na)", th: "กรุณา / นะู้", enSub: "please" },
    { id: 12, en: "(si)", th: "สิ", enSub: "!" },
    { id: 13, en: "(kong)", th: "ของ", enSub: "of" },
    { id: 14, en: "and", th: "และ" },
    { id: 15, en: "or", th: "หรือ" },
    { id: 16, en: "but", th: "แต่" },
    { id: 17, en: "who", th: "ใคร" },
    { id: 18, en: "what", th: "อะไร" },
    { id: 19, en: "where", th: "ที่ไหน" },
    { id: 20, en: "when", th: "เมื่อไร" },
    { id: 21, en: "how", th: "อย่างไร" },
    { id: 22, en: "no", th: "ไม่" },
    { id: 23, en: "yes", th: "ใช่" },
    { id: 24, en: "he/she", th: "เขา" },
    { id: 25, en: "you", th: "เธอ", enSub: "informal" },
    { id: 26, en: "we", th: "เรา" },
    { id: 27, en: "they", th: "พวกเขา" },
    { id: 28, en: "I", th: "ฉัน / ผม" },
    { id: 29, en: "you", th: "คุณ", enSub: "formal" },
  ],
  "grammar 2 - phrases": [
    { id: 1, en: "(songkran)", th: "สงกรานต์" },
    { id: 2, en: "(loy krathong)", th: "ลอยกระทง" },
    { id: 3, en: "chinese new year", th: "วันตรุษจีน" },
    { id: 4, en: "goodbye", th: "ลาก่อน" },
    { id: 5, en: "\"I'll go first\"", th: "ไปก่อนนะ" },
    { id: 6, en: "(joegan)", th: "เจอกัน" },
    { id: 7, en: "sorry", th: "ขอโทษ" },
    { id: 8, en: "\"It's ok\"", th: "ไม่เป็นไร" },
    { id: 9, en: "\"Nice to meet you\"", th: "ยินดีที่ได้รู้จัก" },
    { id: 10, en: "\"Good luck\"", th: "โชคดี" },
    { id: 11, en: "\"Let's go\"", th: " ไปกันเถอะ" },
    { id: 12, en: "\"How are you\"", th: "สบายดีไหม" },
    { id: 13, en: "\"Have you eaten\"", th: "กินข้าวหรือยัง" },
  ],
  "grammar 3 - positions": [
    { id: 1, en: "near", th: "ใกล้" },
    { id: 2, en: "far", th: "ไกล" },
    { id: 3, en: "top", th: "บนตัว", enSub: ".. on top of .." },
    { id: 4, en: "bottom", th: "ก้น", enSub: ".. on the bottom of .." },
    { id: 5, en: "front", th: "หน้า", enSub: ".. in front of .." },
    { id: 6, en: "back", th: "หลัง", enSub: ".. in the back of .." },
    { id: 7, en: "go straight", th: "ตรงไป", },
    { id: 8, en: "go back", th: "กลับมา", },
    { id: 9, en: "turn left", th: "เลี้ยวซ้าย", },
    { id: 10, en: "turn right", th: "เลี้ยวขวา", },
    { id: 11, en: "north", th: "ทิศเหนือ", },
    { id: 12, en: "south", th: "ใต้", },
    { id: 13, en: "east", th: "ทิศตะวันออก", },
    { id: 14, en: "west", th: "ตะวันตก", },
  ],
  "grammar 4 - phrases": [
    { id: 1, en: "\"Great\"", th: "ยอด" },
    { id: 2, en: "\"Sure\"", th: "แน่นอน" },
    { id: 3, en: "\"No way\"", th: "ไม่มีทาง" },
    { id: 4, en: "\"Just a minute\"", th: "เดี๋ยวก่อน" },
    { id: 5, en: "\"Oh no!\"", th: "ตายแล้ว" },
  ],
};

export {
  flashcards,
}
